#!/usr/bin/env tclsh
set SIZE 1024

set file_id [open "include/reciprocal_table.h" r]

while {[gets $file_id line] != -1} {
	if {[regexp {^#define\s+DEPTH_RECIPROCAL_SIZE\s+(\d+)} $line -> value]} {
		set SIZE $value
		break
	}
}


puts "/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
puts "\n\t\tAUTO-GENERATED BY mkrectab.tcl -- DO NOT EDIT\n"
puts "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/"
puts {#include "reciprocal_table.h"}
puts "\n\nconst s32\ndepth_reciprocal\[\] = {"
puts "    0x7FFFFFFF,  /* 0: infinity guard */"

for {set i 1} {$i < $SIZE+1} {incr i} {
    puts "    (YGR_UNITS_PER_SQUARE) / $i,"
}

puts "};"
puts "\nconst s32\ndepth_reciprocal_65536\[\] = {"
puts "    0x7FFFFFFF,"

for {set i 1} {$i < $SIZE+1} {incr i} {
	puts "    65536 / $i,"
}

puts "};"

