#!/usr/bin/env python3
SIZE = 1024

print("/* Auto-generated by gen_reciprocal.py -- do not edit */")
print('#include "reciprocal_table.h"\n')
print("\nconst s32\ndepth_reciprocal[] = {")
print("    0x7FFFFFFF,  /* 0: infinity guard */")
for i in range(1, SIZE):
    print(f"    (YAGBAR_UNITS_PER_SQUARE) / {i},")
print("};")
print("\nconst s32\ndepth_reciprocal_65536[] = {")
print("    0x7FFFFFFF,")
for i in range(1, SIZE):
    print(f"    65536 / {i},")
print("};")

