#include <stdint.h>
#ifndef BUILD_TOOLS
    #include <tonc.h>
#endif /* !BUILD_TOOLS */


#define RGB15(r,g,b) (((r)&31) | (((g)&31)<<5) | (((b)&31)<<10))


#ifdef BUILD_TOOLS
typedef int8_t  s8;
typedef uint8_t u8;
typedef int16_t s16;
// ... your hues table and palette loop here ...
// Instead of writing to pal_bg_mem, collect into:
uint16_t pal_bg_mem[256];
#endif /* BUILD_TOOLS */

// Each row: {r, g, b} at full saturation midpoint
// Ramp goes dark desaturated -> full colour -> light desaturated
static const u8 hues[16][3] = {
    { 31, 31, 31 },  // row 0:  greyscale
    { 20, 20, 12 },  // row 1:  warm grey
    { 20, 10,  0 },  // row 2:  brown
    { 31,  0,  0 },  // row 3:  red
    { 31, 12,  0 },  // row 4:  orange
    { 31, 31,  0 },  // row 5:  yellow
    { 16, 31,  0 },  // row 6:  yellow-green
    {  9, 20,  8 },  // row 7:  green
    {  0, 31, 16 },  // row 8:  teal
    {  0, 31, 31 },  // row 9:  cyan
    {  0, 16, 31 },  // row 10: sky blue
    {  0,  0, 31 },  // row 11: blue
    { 12,  0, 31 },  // row 12: indigo
    { 31,  0, 31 },  // row 13: magenta
    { 31,  0, 16 },  // row 14: rose
    { 31, 16, 16 },  // row 15: pink
};


// ---------------------------------------------------------------------------
// Palette setup
// ---------------------------------------------------------------------------
void 
setupPalette(void)
{
    for (int row = 0; row < 16; row++) {
        for (int shade = 0; shade < 16; shade++) {
            int r, g, b;

            if (row == 0) {
                int v = shade * 2;
                pal_bg_mem[shade] = RGB15(v, v, v);
                continue;
            }

            if (shade < 8) {
                // Dark tint at shade 0 -> full colour at shade 7
                int t = shade + 1;  // 2..9
                r = hues[row][0] * t / 8;
                g = hues[row][1] * t / 8;
                b = hues[row][2] * t / 8;
            }
            else {
                // Full colour -> light pastel, add a little white
                int t = shade - 7;  // 1..8
                r = hues[row][0] + (31 - hues[row][0]) * t / 9;
                g = hues[row][1] + (31 - hues[row][1]) * t / 9;
                b = hues[row][2] + (31 - hues[row][2]) * t / 9;
            }

            pal_bg_mem[row * 16 + shade] = RGB15(r, g, b);
        }
    }
}

#ifdef BUILD_TOOLS
    #include <stdio.h>

    #define STB_IMAGE_WRITE_IMPLEMENTATION
    #include "stb_image_write.h"


static u8 rgb_palette[256][3];


void
populateRGBPalette(void)
{
    for (int i = 0; i < 256; i++) {
        rgb_palette[i][0] = (pal_bg_mem[i]      & 31) << 3;
        rgb_palette[i][1] = (pal_bg_mem[i] >> 5 & 31) << 3;
        rgb_palette[i][2] = (pal_bg_mem[i] >>10 & 31) << 3;
    }
}

void
gimpPalette(void)
{
    printf("GIMP Palette\nName: GBAraycaster\nColumns: 16\n#\n");
    for (int i = 0; i < 256; i++) {
        int r = (pal_bg_mem[i]      & 31) << 3;
        int g = (pal_bg_mem[i] >> 5 & 31) << 3;
        int b = (pal_bg_mem[i] >>10 & 31) << 3;
        printf("%3d %3d %3d\tIndex %d\n", r, g, b, i);
    }
}

void
genCSource(void)
{
    u8
        color,
        base;
    s16
        shaded,
        below_base,
        brightened,
        above_base;
    
    printf(
            "/*!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
            "\n\n\t\tAUTO-GENERATED BY mkpal -- DO NOT EDIT!!\n\n"
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!*/"
            "\n#include \"palette.h\"\n\n"
            "/* BRIGHTNESS LOOKUP TABLE */\n"
            "const unsigned char\nbrightLut[256][17] = {"
        );
    for (s16 x = 0; x < 256; x++) {
        printf("\n\t{ ");
        for (s8 y = 0; y < 17; y++) {
            brightened  = (s16)x + (s16)y;
            s16 row_max = (x & 0xF0) + 15;
            above_base  = brightened - row_max;
            if (above_base > 0) {
                brightened = 15; 
            }
            color = (u8)brightened;
            printf("%3d", color);
            if (y < 16) printf(", ");
        }
        printf(" }");
        if (x < 255) printf(",");
    }
    printf(
            "\n};\n\n/* DARKNESS LOOKUP TABLE */\n"
            "const unsigned char\ndarkLut[256][17] = {"
        );
    for (s16 x = 0; x < 256; x++) {
        printf("\n\t{ ");
        for (s8 y = 0; y < 17; y++) {
            shaded      = (s16)x - (s16)y;
            shaded     &= ~(shaded >> 15);                    // clamp to 0 if negative
            below_base  = shaded - (s16)(x & 0xF0);           // check against ROW BASE
            shaded     &= ~(below_base >> 15);                // clamp to row_base if crossed
            color       = (u8)shaded;
            printf("%3d", color);
            if (y < 16) printf(", ");
        }
        printf(" }");
        if (x < 255) printf(",");
    }
    printf("\n};");
}

void
handleArgs(int argc, char **argv)
{
	for (int i = 1; i < argc; i++) {
		char *c = &argv[i][2];
		if (argv[i][0] == '-') {
			switch (argv[i][1]) {
			case 'g':
				gimpPalette();
				break;
			case 'c':
			    genCSource();
				break;
			case 'i':
			    switch ((char)*c) {
                case 't':
                    stbi_write_tga("palette.tga", 16, 16, 3, rgb_palette);
                    break;
                case 'b':
                    stbi_write_bmp("palette.bmp", 16, 16, 3, rgb_palette);
                    break;
			    case 'p': /* FALLTHROUGH */
			    default:
                    stbi_write_png("palette.png", 16, 16, 3, rgb_palette, 16 * 3);
			    }
			    break;
			default:
				printf("Malformed argument %c\n", argv[i][1]);
			}
		}
		else printf("Malformed argument %c\n", argv[i][0]);
	}
}
    
int main(int argc, char **argv) {
    setupPalette();
	stbi_write_tga_with_rle = 0;
	populateRGBPalette();
    // then dump:
    handleArgs(argc, argv);
}

#endif /* BUILD_TOOLS */
